language: php

before_script:
  - composer install --dev --no-interaction

script:
  - vendor/bin/phpunit test/unit --filter test* --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
