language: php
php:
- 5.6
- 7.0
- 7.1
- 7.2
- 7.3
- 7.4
env:
  matrix:
  - dependencies=lowest
  - dependencies=highest
  global:
  - composer_flags="--no-interaction --no-ansi --no-progress --no-suggest --verbose"
before_install:
- composer self-update
- composer clear-cache
install:
- if [ -n "$GIT_HUB_TOKEN" ]; then composer config -g github-oauth.github.com "$GIT_HUB_TOKEN";
  fi;
- if [ "$dependencies" = "highest" ]; then composer update $composer_flags; fi;
- if [ "$dependencies" = "lowest" ]; then composer update $composer_flags --prefer-lowest
  --prefer-stable; fi;
script:
- vendor/bin/phpunit test/unit
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  slack:
    if: branch = main
    on_pull_requests: false
    on_success: never
    on_failure: change
    rooms:
      secure: EW/neaxTh/KtmV2DB1f3D2vVokKicWFE95t/dFyvwdsg0xW3lZdy2dO1JhOVdetqB4JUpKt5euwgvAf0QMiOVtn4eKhan2viLkK0SIYKy89T+Q8h+QlUNksdUSBGSDTYTs/CwC7408nOgGzGKdwVlr2uHrOnruN3OgMgikXMDykmzucUoiN8NeS1rMrjkRG5VqjnA2zkhhTyRfYBuM14hy6g8KDXQWUDRsdty7N7hwALe1R/h9jULSKUWh2eY2zsv6KVFvlsHABBCYUBSE9SRNH5QigkR1D0iLbaRixyfPOdza2vHq4blsQKLKf2j4XTV8hP+o0Mce8hmEFx9M4K66EpoYZDFsBQgB9kQGaCP6GuOH/isnujOGu0YmKrHruB6ByK0Exec4XuwrdI3IWYAe1EjHfa9yC1dJ1MR8rEGgsNCSrJcjlbH8XWgelMprLnCSciKM0uEt11k6ogHd9plE6T2cXEwrtDPGa9FwkIfDeOE6AndF9PkoCptiFpH/PKRfouc9UqYUZTsSTf556GciHOelMphNey0ODIbpZc8NwwgnMwFeHwnx8l0olZvjhFtnkESmdegO26WYA4dYKrykQNc96yz2iji8hbE/NYoyNLv54DDhDH0cTDMYqGfJXGvVcB48kP2BT5A8inGXCL7QgjT0LKNb0kYBXw669Olvk=
