name: Test
on:
  push:
    branches: [ '*' ]
    tags: [ '*' ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run automatically at 8AM PST Monday-Friday
    - cron: '0 15 * * 1-5'
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        php: [ 5.6, 7.0, 7.1, 7.2, 7.3, 7.4 ]
        dependencies:
          - "lowest"
          - "highest"

    steps:
      -   name: Checkout php-http-client
          uses: actions/checkout@v2

      -   name: Setup PHP Action
          uses: shivammathur/setup-php@2.15.0
          with:
            php-version: ${{ matrix.php }}
          id: php

      -   name: Composer webhook config
          run: composer config -g github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}

      -   name: Install dependencies
          run: composer install

      -   name: Update Dependencies
          if: ${{ matrix.dependencies == 'lowest' }}
          run: composer update --prefer-lowest --prefer-stable -n

      -   name: Run Tests
          run: make test

  notify-on-failure:
    name: Slack notify on failure
    if: ${{ failure() && github.ref == 'refs/heads/main' && github.event_name != 'pull_request' }}
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: failure
          SLACK_ICON_EMOJI: ':github:'
          SLACK_MESSAGE: ${{ format('Build {2} in {1} failed{3} {0}/{1}/actions/runs/{2}', github.server_url, github.repository, github.run_id, ':') }}
          SLACK_TITLE: Build Failure
          SLACK_USERNAME: GitHub Actions
          SLACK_MSG_AUTHOR: twilio-dx
          SLACK_FOOTER: Posted automatically using GitHub Actions
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          MSG_MINIMAL: true
